replicaCount: 1
image:
  tag: "1.0.0-dev"
  pullPolicy: Always
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: false
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: JAVA_OPTS
    value: "-Xms64m -Xmx128m"
  - name: LOG_LEVEL
    value: "DEBUG"
database:
  host: postgres-dev-service
  port: 5432
  name: three_tier_dev
  username: devuser
  passwordSecret: postgres-dev-secret
podDisruptionBudget:
  enabled: false
