apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-service.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      application:
        name: order-service
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
      datasource:
        hikari:
          maximum-pool-size: 20
          minimum-idle: 5
    logging:
      level:
        root: {{ .Values.logging.level }}
        com.example: DEBUG
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
